### ISSUE TITLE
minimum package version

### ISSUE THREAD

**Issue by fredz999** [AudioKit/AudioKitSPM#1]
when I paste 'https://github.com/AudioKit/AudioKitSPM' into my package managers repo search It retrieves the repository but the  versions aren't auto filled, when I hit the 'next' button it won't proceed with a warning message about the minimum version not being filled out.
I tried guessing 0 and 1 as minimum versions with no luck, any ideas?

**Comment by megastep** [comment]
Are you doing this in Xcode 12?

**Comment by megastep** [comment]
Right now there's no published version as it's preliminary but it should work if you just tell it to use the master branch.

**Comment by fredz999** [comment]
right,.... went into the dialog and specified master branch, it didn't give an error this time but it hung on the loading screen for a very long time, I pressed cancel and tried to reload it and it told me another package operation is in progress, am I doing something wrong?

**Comment by fredz999** [comment]
you want to leave this till tomorrow?

**Comment by megastep** [comment]
Mmh, I don't know, haven't tried with the latest beta of Xcode 12, maybe something changed. It's a pretty sizable download though so maybe it's taking more time for you.

**Comment by aure** [comment]
We're working on a different kind of SPM based solution if you're willing to wait a few days.

**Comment by aure** [comment]
Hi there, so I just confirmed you can use SPM to start a new project pointing to the Github URL for the AudioKit package. Just make sure to use the v5-develop branch and also know you're very much on the cutting edge. In addition to closing this issue, I suggest we delete this repository.

**Comment by fredz999** [comment]
ta
